services:

  #POSTGRESQL
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: between_us
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - between-us
    restart: unless-stopped

  #KEYCLOAK
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.2.0
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    networks:
      - between-us
    command:
      - "start-dev"

networks:
  between-us:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local